export type SentinelView = 'OK' | 'SDOWN' | 'ODOWN'
export type NodeReachability = 'up' | 'down'
export type RedisRole = 'master' | 'replica'
export type ReplicaRole = 'replica' | 'candidate' | 'selected' | 'promoting' | 'master'
export type MessageKind = 'probe' | 'confirm' | 'vote' | 'decision' | 'command' | 'sync'
export type RedisNodeId = 'm0' | 'r1' | 'r2'

export interface RedisEventRoute {
  from: string
  to: string
}

export interface RedisEvent {
  route: RedisEventRoute | null
  label: string
  kind: MessageKind
}

export interface RedisFrame {
  id: string
  phase: string
  title: string
  description: string
  context: string
  topology: string
  epoch: number | null
  m0Reachability: NodeReachability
  m0Role: RedisRole
  sentinelViews: SentinelView[]
  leader: string | null
  r1Role: ReplicaRole
  r2Role: ReplicaRole
  r1Upstream: 'm0' | null
  r2Upstream: 'm0' | 'r1'
  m0Upstream: 'r1' | null
  quorumVotes: number
  authorizationVotes: number
  event: RedisEvent
}

const initialTopology = '配置拓扑：R1 ← M0 → R2'
const failedTopology = '复制中断：R1 ←× M0 ×→ R2'

export const redisFrames: RedisFrame[] = [
  {
    id: 'healthy',
    phase: '正常监控',
    title: '主从复制稳定运行',
    description: 'M0 提供写服务，R1、R2 持续复制；Sentinel 周期性发送 PING 与 INFO。',
    context: 'down-after 5,000 ms',
    topology: initialTopology,
    epoch: null,
    m0Reachability: 'up',
    m0Role: 'master',
    sentinelViews: ['OK', 'OK', 'OK', 'OK', 'OK'],
    leader: null,
    r1Role: 'replica',
    r2Role: 'replica',
    r1Upstream: 'm0',
    r2Upstream: 'm0',
    m0Upstream: null,
    quorumVotes: 0,
    authorizationVotes: 0,
    event: { route: { from: 'm0', to: 'r1' }, label: 'PSYNC 复制流', kind: 'sync' },
  },
  {
    id: 'master-unreachable',
    phase: '真实故障',
    title: 'M0 停止响应',
    description: 'S1 的 PING 没有收到有效回复；超时阈值尚未达到，所以不会立即判定下线。',
    context: 'PING · no reply',
    topology: failedTopology,
    epoch: null,
    m0Reachability: 'down',
    m0Role: 'master',
    sentinelViews: ['OK', 'OK', 'OK', 'OK', 'OK'],
    leader: null,
    r1Role: 'replica',
    r2Role: 'replica',
    r1Upstream: 'm0',
    r2Upstream: 'm0',
    m0Upstream: null,
    quorumVotes: 0,
    authorizationVotes: 0,
    event: { route: { from: 's1', to: 'm0' }, label: 'PING（无 PONG）', kind: 'probe' },
  },
  {
    id: 's1-sdown',
    phase: '主观下线',
    title: 'S1 本地判定 SDOWN',
    description: 'S1 连续 5 秒未收到有效回复，只更新自己的本地视图；其他 Sentinel 不会自动同步该结论。',
    context: 'S1 · elapsed 5,000 ms',
    topology: failedTopology,
    epoch: null,
    m0Reachability: 'down',
    m0Role: 'master',
    sentinelViews: ['SDOWN', 'OK', 'OK', 'OK', 'OK'],
    leader: null,
    r1Role: 'replica',
    r2Role: 'replica',
    r1Upstream: 'm0',
    r2Upstream: 'm0',
    m0Upstream: null,
    quorumVotes: 1,
    authorizationVotes: 0,
    event: { route: { from: 's1', to: 'm0' }, label: '超时 ≥ 5,000 ms', kind: 'probe' },
  },
  {
    id: 's2-sdown',
    phase: '主观下线',
    title: 'S2 独立判定 SDOWN',
    description: 'S2 也在自己的计时器上达到超时，但 S1 尚未收到 S2 的判断，因此仍只有 1 票。',
    context: 'S2 · elapsed 5,000 ms',
    topology: failedTopology,
    epoch: null,
    m0Reachability: 'down',
    m0Role: 'master',
    sentinelViews: ['SDOWN', 'SDOWN', 'OK', 'OK', 'OK'],
    leader: null,
    r1Role: 'replica',
    r2Role: 'replica',
    r1Upstream: 'm0',
    r2Upstream: 'm0',
    m0Upstream: null,
    quorumVotes: 1,
    authorizationVotes: 0,
    event: { route: { from: 's2', to: 'm0' }, label: '超时 ≥ 5,000 ms', kind: 'probe' },
  },
  {
    id: 'ask-down-state',
    phase: '客观下线',
    title: 'S1 向 S2 询问主库状态',
    description: 'S1 通过 Sentinel 间的询问收集独立判断；发出请求本身还不会形成 ODOWN。',
    context: 'quorum 1 / 2',
    topology: failedTopology,
    epoch: null,
    m0Reachability: 'down',
    m0Role: 'master',
    sentinelViews: ['SDOWN', 'SDOWN', 'OK', 'OK', 'OK'],
    leader: null,
    r1Role: 'replica',
    r2Role: 'replica',
    r1Upstream: 'm0',
    r2Upstream: 'm0',
    m0Upstream: null,
    quorumVotes: 1,
    authorizationVotes: 0,
    event: { route: { from: 's1', to: 's2' }, label: 'is-master-down-by-addr?', kind: 'confirm' },
  },
  {
    id: 's1-odown',
    phase: '客观下线',
    title: 'S2 的回复使 S1 达到 quorum',
    description: 'S1 收到 S2 的 down_state=1；2 票达到 quorum，因此只有 S1 的视图升级为 ODOWN。',
    context: 'quorum 2 / 2',
    topology: failedTopology,
    epoch: null,
    m0Reachability: 'down',
    m0Role: 'master',
    sentinelViews: ['ODOWN', 'SDOWN', 'OK', 'OK', 'OK'],
    leader: null,
    r1Role: 'replica',
    r2Role: 'replica',
    r1Upstream: 'm0',
    r2Upstream: 'm0',
    m0Upstream: null,
    quorumVotes: 2,
    authorizationVotes: 0,
    event: { route: { from: 's2', to: 's1' }, label: 'down_state=1', kind: 'confirm' },
  },
  {
    id: 'election-start',
    phase: '协调者选举',
    title: 'S1 开启 epoch 42 并先投自己',
    description: 'S1 带着自己的 1 票请求 S2 授权；ODOWN 的 quorum 与协调者多数派是两套门槛。',
    context: 'epoch 42 · votes 1 / 5',
    topology: failedTopology,
    epoch: 42,
    m0Reachability: 'down',
    m0Role: 'master',
    sentinelViews: ['ODOWN', 'SDOWN', 'OK', 'OK', 'OK'],
    leader: null,
    r1Role: 'replica',
    r2Role: 'replica',
    r1Upstream: 'm0',
    r2Upstream: 'm0',
    m0Upstream: null,
    quorumVotes: 2,
    authorizationVotes: 1,
    event: { route: { from: 's1', to: 's2' }, label: '请求授权 · epoch 42', kind: 'vote' },
  },
  {
    id: 'vote-s2',
    phase: '协调者选举',
    title: 'S2 在 epoch 42 授权 S1',
    description: 'S2 在同一 epoch 内只能投出一票；S1 现在有 2 票，仍未达到 5 个 Sentinel 的多数派。',
    context: 'epoch 42 · votes 2 / 5',
    topology: failedTopology,
    epoch: 42,
    m0Reachability: 'down',
    m0Role: 'master',
    sentinelViews: ['ODOWN', 'SDOWN', 'OK', 'OK', 'OK'],
    leader: null,
    r1Role: 'replica',
    r2Role: 'replica',
    r1Upstream: 'm0',
    r2Upstream: 'm0',
    m0Upstream: null,
    quorumVotes: 2,
    authorizationVotes: 2,
    event: { route: { from: 's2', to: 's1' }, label: 'vote=S1 · epoch 42', kind: 'vote' },
  },
  {
    id: 'vote-s3',
    phase: '协调者选举',
    title: 'S3 投出决定性一票',
    description: 'S1 获得 3/5 多数派授权，成为 epoch 42 这一轮故障转移的临时协调者。',
    context: 'epoch 42 · coordinator S1',
    topology: failedTopology,
    epoch: 42,
    m0Reachability: 'down',
    m0Role: 'master',
    sentinelViews: ['ODOWN', 'SDOWN', 'OK', 'OK', 'OK'],
    leader: 's1',
    r1Role: 'replica',
    r2Role: 'replica',
    r1Upstream: 'm0',
    r2Upstream: 'm0',
    m0Upstream: null,
    quorumVotes: 2,
    authorizationVotes: 3,
    event: { route: { from: 's3', to: 's1' }, label: 'vote=S1 · epoch 42', kind: 'vote' },
  },
  {
    id: 'select-replica',
    phase: '选择副本',
    title: 'S1 选择 R1 作为晋升目标',
    description: '两者 priority 都是 100；继续比较复制偏移量后，R1 的 1200 高于 R2 的 1160。',
    context: 'priority asc · offset desc',
    topology: failedTopology,
    epoch: 42,
    m0Reachability: 'down',
    m0Role: 'master',
    sentinelViews: ['ODOWN', 'SDOWN', 'OK', 'OK', 'OK'],
    leader: 's1',
    r1Role: 'selected',
    r2Role: 'candidate',
    r1Upstream: 'm0',
    r2Upstream: 'm0',
    m0Upstream: null,
    quorumVotes: 2,
    authorizationVotes: 3,
    event: { route: null, label: 'R1 · offset 1200 > 1160', kind: 'decision' },
  },
  {
    id: 'promote-command',
    phase: '执行晋升',
    title: 'S1 命令 R1 脱离复制',
    description: 'REPLICAOF NO ONE 已发出；R1 进入 PROMOTING，但在实际回报角色前还不能视为主库。',
    context: 'SEND_SLAVEOF_NOONE',
    topology: '晋升中：R1 脱离 M0 · R2 仍指向 M0',
    epoch: 42,
    m0Reachability: 'down',
    m0Role: 'master',
    sentinelViews: ['ODOWN', 'SDOWN', 'OK', 'OK', 'OK'],
    leader: 's1',
    r1Role: 'promoting',
    r2Role: 'replica',
    r1Upstream: null,
    r2Upstream: 'm0',
    m0Upstream: null,
    quorumVotes: 2,
    authorizationVotes: 3,
    event: { route: { from: 's1', to: 'r1' }, label: 'REPLICAOF NO ONE', kind: 'command' },
  },
  {
    id: 'promotion-confirmed',
    phase: '确认晋升',
    title: 'R1 实际回报 master 角色',
    description: 'S1 从 INFO 中确认 R1 已成为新主库；此时 R2 仍配置为复制失效的 M0。',
    context: 'WAIT_PROMOTION',
    topology: '新主已确认：R1 · R2 仍指向 M0',
    epoch: 42,
    m0Reachability: 'down',
    m0Role: 'master',
    sentinelViews: ['ODOWN', 'SDOWN', 'OK', 'OK', 'OK'],
    leader: 's1',
    r1Role: 'master',
    r2Role: 'replica',
    r1Upstream: null,
    r2Upstream: 'm0',
    m0Upstream: null,
    quorumVotes: 2,
    authorizationVotes: 3,
    event: { route: { from: 'r1', to: 's1' }, label: 'INFO · role=master', kind: 'confirm' },
  },
  {
    id: 'reconfigure-r2',
    phase: '重配置副本',
    title: 'S1 将 R2 切换到 R1',
    description: 'S1 向 R2 发送新的复制目标；R2 开始复制 R1，而旧主 M0 仍不可达。',
    context: 'RECONF_SLAVES · parallel 1',
    topology: '切换中：R1 → R2 · M0 仍离线',
    epoch: 42,
    m0Reachability: 'down',
    m0Role: 'master',
    sentinelViews: ['ODOWN', 'SDOWN', 'OK', 'OK', 'OK'],
    leader: 's1',
    r1Role: 'master',
    r2Role: 'replica',
    r1Upstream: null,
    r2Upstream: 'r1',
    m0Upstream: null,
    quorumVotes: 2,
    authorizationVotes: 3,
    event: { route: { from: 's1', to: 'r2' }, label: 'REPLICAOF R1 6379', kind: 'command' },
  },
  {
    id: 'old-master-recovers',
    phase: '旧主恢复',
    title: 'M0 恢复连接但仍自认为 master',
    description: '当前配置主库已经是 R1；M0 恢复后先报告旧角色，等待 Sentinel 下发重配置命令。',
    context: 'M0 · role=master · pending',
    topology: '待处理：M0（旧 MASTER）· R1 → R2',
    epoch: 42,
    m0Reachability: 'up',
    m0Role: 'master',
    sentinelViews: ['OK', 'OK', 'OK', 'OK', 'OK'],
    leader: 's1',
    r1Role: 'master',
    r2Role: 'replica',
    r1Upstream: null,
    r2Upstream: 'r1',
    m0Upstream: null,
    quorumVotes: 2,
    authorizationVotes: 3,
    event: { route: { from: 'm0', to: 's1' }, label: 'PONG + INFO role=master', kind: 'confirm' },
  },
  {
    id: 'reconfigure-old-master',
    phase: '拓扑收敛',
    title: 'S1 将旧主 M0 改为副本',
    description: 'M0 接受 REPLICAOF R1，最终与 R2 一起复制 R1；旧主恢复后不会自动抢回主角色。',
    context: 'UPDATE_CONFIG · completed',
    topology: '新拓扑：M0 ← R1 → R2',
    epoch: 42,
    m0Reachability: 'up',
    m0Role: 'replica',
    sentinelViews: ['OK', 'OK', 'OK', 'OK', 'OK'],
    leader: 's1',
    r1Role: 'master',
    r2Role: 'replica',
    r1Upstream: null,
    r2Upstream: 'r1',
    m0Upstream: 'r1',
    quorumVotes: 2,
    authorizationVotes: 3,
    event: { route: { from: 's1', to: 'm0' }, label: 'REPLICAOF R1 6379', kind: 'command' },
  },
]

export const sentinelPositions = [
  { id: 's1', label: 'S1', x: 110, y: 96 },
  { id: 's2', label: 'S2', x: 290, y: 96 },
  { id: 's3', label: 'S3', x: 470, y: 96 },
  { id: 's4', label: 'S4', x: 650, y: 96 },
  { id: 's5', label: 'S5', x: 830, y: 96 },
]

export const redisNodePositions = [
  { id: 'm0', label: 'M0', x: 170, y: 360 },
  { id: 'r1', label: 'R1', x: 470, y: 360 },
  { id: 'r2', label: 'R2', x: 770, y: 360 },
]
